# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [143]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [144]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df.tail(60)

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
740,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False
742,Pancham,Fighting,NaN,67,82,62,46,48,43,6,False
743,Pangoro,Fighting,Dark,95,124,78,69,71,58,6,False
744,Furfrou,Normal,NaN,75,80,60,65,90,102,6,False
745,Espurr,Psychic,NaN,62,48,54,63,60,68,6,False
746,Meowstic Male,Psychic,NaN,74,48,76,83,81,104,6,False
747,Meowstic Female,Psychic,NaN,74,48,76,83,81,104,6,False
748,Honedge,Steel,Ghost,45,80,100,35,37,28,6,False
749,Doublade,Steel,Ghost,59,110,150,45,49,35,6,False
750,Aegislash Blade Forme,Steel,Ghost,60,150,50,150,50,60,6,False
751,Aegislash Shield Forme,Steel,Ghost,60,50,150,50,150,60,6,False
752,Spritzee,Fairy,NaN,78,52,60,63,65,23,6,False
753,Aromatisse,Fairy,NaN,101,72,72,99,89,29,6,False
754,Swirlix,Fairy,NaN,62,48,66,59,57,49,6,False
755,Slurpuff,Fairy,NaN,82,80,86,85,75,72,6,False
756,Inkay,Dark,Psychic,53,54,53,37,46,45,6,False
757,Malamar,Dark,Psychic,86,92,88,68,75,73,6,False
758,Binacle,Rock,Water,42,52,67,39,56,50,6,False
759,Barbaracle,Rock,Water,72,105,115,54,86,68,6,False
760,Skrelp,Poison,Water,50,60,60,60,60,30,6,False
761,Dragalge,Poison,Dragon,65,75,90,97,123,44,6,False
762,Clauncher,Water,NaN,50,53,62,58,63,44,6,False
763,Clawitzer,Water,NaN,71,73,88,120,89,59,6,False
764,Helioptile,Electric,Normal,44,38,33,61,43,70,6,False
765,Heliolisk,Electric,Normal,62,55,52,109,94,109,6,False
766,Tyrunt,Rock,Dragon,58,89,77,45,45,48,6,False
767,Tyrantrum,Rock,Dragon,82,121,119,69,59,71,6,False
768,Amaura,Rock,Ice,77,59,50,67,63,46,6,False
769,Aurorus,Rock,Ice,123,77,72,99,92,58,6,False
770,Sylveon,Fairy,NaN,95,65,65,110,130,60,6,False
771,Hawlucha,Fighting,Flying,78,92,75,74,63,118,6,False
772,Dedenne,Electric,Fairy,67,58,57,81,67,101,6,False
773,Carbink,Rock,Fairy,50,50,150,50,150,50,6,False
774,Goomy,Dragon,NaN,45,50,35,55,75,40,6,False
775,Sliggoo,Dragon,NaN,68,75,53,83,113,60,6,False
776,Goodra,Dragon,NaN,90,100,70,110,150,80,6,False
777,Klefki,Steel,Fairy,57,80,91,80,87,75,6,False
778,Phantump,Ghost,Grass,43,70,48,50,60,38,6,False
779,Trevenant,Ghost,Grass,85,110,76,65,82,56,6,False
780,Pumpkaboo Average Size,Ghost,Grass,49,66,70,44,55,51,6,False
781,Pumpkaboo Small Size,Ghost,Grass,44,66,70,44,55,56,6,False
782,Pumpkaboo Large Size,Ghost,Grass,54,66,70,44,55,46,6,False
783,Pumpkaboo Super Size,Ghost,Grass,59,66,70,44,55,41,6,False
784,Gourgeist Average Size,Ghost,Grass,65,90,122,58,75,84,6,False
785,Gourgeist Small Size,Ghost,Grass,55,85,122,58,75,99,6,False
786,Gourgeist Large Size,Ghost,Grass,75,95,122,58,75,69,6,False
787,Gourgeist Super Size,Ghost,Grass,85,100,122,58,75,54,6,False
788,Bergmite,Ice,NaN,55,69,85,32,35,28,6,False
789,Avalugg,Ice,NaN,95,117,184,44,46,28,6,False
790,Noibat,Flying,Dragon,40,30,35,45,40,55,6,False
791,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False
792,Xerneas,Fairy,NaN,126,131,95,131,98,99,6,True
793,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
794,Zygarde Half Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [145]:
#code here
df_dragon = df[df["Type 1"]=="Dragon"]["HP"]
df_grass = df[df["Type 1"]=="Grass"]["HP"]

In [146]:
alpha = 0.05
stat, p_value = st.ttest_ind(df_dragon,df_grass, equal_var=False)
#H0= Mu df1 = Mu df2 , H1= Mu df1 =! Mu df2
if p_value > alpha:
    print("We are not able to reject the null hypothesis")
else:
    print("We reject the null hypotesis")

We reject the null hypotesis

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [147]:
#code here
df_legendary_hp = df[(df["Legendary"]=="True")]["HP"]
df_non_legendary_hp = df[(df["Legendary"]=="False")]["HP"]

In [148]:
df_legendary_defense = df[(df["Legendary"]=="True")]["Defense"]
df_non_legendary_defense = df[(df["Legendary"]=="False")]["Defense"]

In [149]:
df_legendary_attack = df[(df["Legendary"]=="True")]["Attack"] 
df_non_legendary_attack = df[(df["Legendary"]=="False")]["Attack"]

In [150]:
df_legendary_spatk = df[(df["Legendary"]=="True")]["Sp. Atk"] 
df_non_legendary_spatk = df[(df["Legendary"]=="False")]["Sp. Atk"]

In [151]:
df_legendary_spdef = df[(df["Legendary"]=="True")]["Sp. Def"] 
df_non_legendary_spdef = df[(df["Legendary"]=="False")]["Sp. Def"]

In [152]:
df_legendary_speed = df[(df["Legendary"]=="True")]["Speed"] 
df_non_legendary_speed = df[(df["Legendary"]=="False")]["Speed"]

In [153]:
alpha = 0.05
stat, p_value = st.ttest_ind(df_legendary_hp,df_non_legendary_hp, equal_var=False)
#H0= Mu df1 = Mu df2 , H1= Mu df1 =! Mu df2
if p_value > alpha:
    print("We are not able to reject the null hypothesis")
else:
    print("We reject the null hypotesis")

We reject the null hypotesis

In [154]:
alpha = 0.05
stat, p_value = st.ttest_ind(df_legendary_attack,df_non_legendary_attack, equal_var=False)
#H0= Mu df1 = Mu df2 , H1= Mu df1 =! Mu df2
if p_value > alpha:
    print("We are not able to reject the null hypothesis")
else:
    print("We reject the null hypotesis")

We reject the null hypotesis

In [155]:
alpha = 0.05
stat, p_value = st.ttest_ind(df_legendary_defense,df_non_legendary_defense, equal_var=False)
#H0= Mu df1 = Mu df2 , H1= Mu df1 =! Mu df2
if p_value > alpha:
    print("We are not able to reject the null hypothesis")
else:
    print("We reject the null hypotesis")

We reject the null hypotesis

In [156]:
alpha = 0.05
stat, p_value = st.ttest_ind(df_legendary_spatk,df_non_legendary_spatk, equal_var=False)
#H0= Mu df1 = Mu df2 , H1= Mu df1 =! Mu df2
if p_value > alpha:
    print("We are not able to reject the null hypothesis")
else:
    print("We reject the null hypotesis")

We reject the null hypotesis

In [157]:
alpha = 0.05
stat, p_value = st.ttest_ind(df_legendary_spdef,df_non_legendary_spdef, equal_var=False)
#H0= Mu df1 = Mu df2 , H1= Mu df1 =! Mu df2
if p_value > alpha:
    print("We are not able to reject the null hypothesis")
else:
    print("We reject the null hypotesis")

We reject the null hypotesis

In [158]:
alpha = 0.05
stat, p_value = st.ttest_ind(df_legendary_speed,df_non_legendary_speed, equal_var=False)
#H0= Mu df1 = Mu df2 , H1= Mu df1 =! Mu df2
if p_value > alpha:
    print("We are not able to reject the null hypothesis")
else:
    print("We reject the null hypotesis")

We reject the null hypotesis

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [159]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 37)
- Hospital coordinates (-122, 34)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [160]:
import math

In [161]:
def distancia_euclidiana(x1, y1, x2, y2):
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

school_coords = (-118, 37)
hospital_coords = (-122, 34)

df['distancia_escuela'] = df.apply(lambda row: distancia_euclidiana(row['longitude'], row['latitude'], school_coords[0], school_coords[1]), axis=1) 
df['distancia_hospital'] = df.apply(lambda row: distancia_euclidiana(row['longitude'], row['latitude'], hospital_coords[0], hospital_coords[1]), axis=1)

In [164]:
df_cerca_escuela = df[df["distancia_escuela"]<0.5]["median_house_value"]
df_lejos_escuela = df[df["distancia_escuela"]>0.5]["median_house_value"]

In [165]:
alpha=0.05

In [166]:
stat, p_value = st.ttest_ind(df_cerca_escuela,df_lejos_escuela,equal_var=False, alternative="less")
#H0= Mu df1 >= Mu df2 , 
# H1= Mu df1 < Mu df2
if p_value > alpha:
    print("We are not able to reject the null hypothesis")
else:
    print("We reject the null hypotesis")

We reject the null hypotesis